image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
    only:
        - master  # ветка git

build: off  # будем использовать свой скрипт сборки

install:
    # запускаем SUT (& означает, что в фоновом режиме - не блокируем терминал для запуска тестов)
    - sudo curl -L "https://github.com/docker/compose/releases/download/1.28.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    - sleep 15
    - sudo chmod +x /usr/local/bin/docker-compose
    - docker-compose up -d
    - sleep 15
    - java "-Dspring.datasource.url=jdbc:postgresql://localhost:5432/app" -jar artifacts/aqa-shop.jar &
    - sleep 15
build_script:
    - chmod +x gradlew
    - ./gradlew test --info "-Dselenide.headless=true"  # запускаем тест, флаг --info позволяет выводить больше информации